# Generated by Django 4.0.5 on 2022-06-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panchos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descrição', models.TextField(blank=True, verbose_name='descrição')),
                ('preço', models.CharField(max_length=100, verbose_name='preço')),
            ],
        ),
    ]
