# Generated by Django 4.0.5 on 2022-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=200, verbose_name='telefone')),
            ],
        ),
    ]
