# Generated by Django 4.0.5 on 2022-07-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burguer',
            old_name='descricao',
            new_name='descricao2',
        ),
    ]
