# Generated by Django 4.0.5 on 2022-07-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0002_rename_descricao_burguer_descricao2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burguer',
            old_name='descricao2',
            new_name='descricao',
        ),
    ]
