# Generated by Django 4.0.5 on 2022-06-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0003_alter_panchos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descrição', models.TextField(blank=True, verbose_name='descrição')),
                ('preço', models.CharField(max_length=100, verbose_name='preço')),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Burguer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descrição', models.TextField(blank=True, verbose_name='descrição')),
                ('preço', models.CharField(max_length=100, verbose_name='preço')),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Fritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descrição', models.TextField(blank=True, verbose_name='descrição')),
                ('preço', models.CharField(max_length=100, verbose_name='preço')),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/')),
            ],
        ),
    ]
