# Generated by Django 4.0.5 on 2022-07-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0004_frita_bebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=1000)),
                ('preco', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=800)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amigos_panchos.categoria')),
            ],
        ),
    ]
