# Generated by Django 4.0.5 on 2022-06-30 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0004_bebidas_burguer_fritas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigos_panchos.panchos')),
            ],
        ),
    ]
