# Generated by Django 4.0.5 on 2022-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0005_xi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pancho',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m'),
        ),
    ]
