# Generated by Django 4.0.5 on 2022-06-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0005_lanches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lanches',
        ),
    ]
