# Generated by Django 4.0.5 on 2022-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0006_pancho_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotosBebidas/%Y/%m'),
        ),
        migrations.AddField(
            model_name='burguer',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotosBurguer/%Y/%m'),
        ),
        migrations.AddField(
            model_name='frita',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotosFritas/%Y/%m'),
        ),
        migrations.AddField(
            model_name='xi',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotosXis/%Y/%m'),
        ),
    ]
