# Generated by Django 4.0.5 on 2022-07-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_panchos', '0009_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
